In [2]:
#Nome: Alberto Rodrigues Ferreira
#Matrícula: 391278
import numpy as np
import itertools as it

In [3]:
#Processo que pede numero de observacoes, variaveis e o grau da funcao 
#de disjuncao sem nenhum problema.
while True:
    try:
        n=int(input("Digite o número de observacoes: "))
        p=int(input("Digite o número de variaveis: "))
        if p>0 and n>0 and float(p)==int(p) and float(n)==int(n):
            break
        else:
            print("Voce nao digitou as quantidades pedidas adequadamente, tente denovo!")
    except:
        print("Voce nao digitou as quantidades pedidas adequadamente, tente denovo!")

Digite o número de observacoes: 100
Digite o número de variaveis: 8


In [4]:
while True:
    try:
        k=int(input("Digite o grau do maior monomio da disjuncao: "))
        if k>0 and float(k)==int(k) and k<=p:
            break
        elif k>p:
             print("Voce digitou um grau maior que o numero de variaveis, tente denovo!")
        else:
            print("Voce nao digitou o grau adequadamente, tente denovo!")
    except:
        print("Voce nao digitou o grau adequadamente, tente denovo!")     


Digite o grau do maior monomio da disjuncao: 9
Voce digitou um grau maior que o numero de variaveis, tente denovo!
Digite o grau do maior monomio da disjuncao: 3


In [5]:
amostra=np.random.randint(0,2,size=(n,p))
#Gerando todos os monomios possiveis.
Monomios=list(it.product([-1,0,1],repeat=p))


In [6]:
#Tirando o monomios que nao pega nenhum literal.
Monomios.remove(tuple(np.full(p,0)))
#Removendo monomios que passam do limite de grau k generico fornecido pelo usuario.
monomios_a_remover=[]
for i in Monomios:
    if i.count(0)<p-k:
        monomios_a_remover.append(i)
monomios_a_remover  
for i in monomios_a_remover:
    Monomios.remove(i)   
Monomios=np.array(Monomios)


In [7]:
#Aqui escolho os indices de alguns monomios possiveis para gerar as classes 
#da amostra, por simplicidade gerei uma funcao de disjuncao que tem no maximo
#5 monomios se tiver pelo menos 2 variaveis e se tiver 1 variavel sera so 1
#monomio, pois quanto maior o numero de monomios que gerarao as classes e mais
#provavel da classe ser 1.
if p>1:
    IndicesAleatorios=np.random.choice(np.arange(len(Monomios)),np.random.choice(np.arange(1,6)),replace=False)
else:
    IndicesAleatorios=np.random.choice(np.arange(len(Monomios)),1,replace=False)
IndicesAleatorios


array([265, 430, 207, 148, 213])

In [8]:
#Funcao de disjuncao que gerará as classes
previsores_classes=Monomios[IndicesAleatorios]
previsores_classes


array([[ 0,  0,  0,  0, -1,  0,  0,  0],
       [ 0,  1,  0,  0, -1,  1,  0,  0],
       [ 0,  0, -1,  0,  1, -1,  0,  0],
       [ 0, -1,  0,  0,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  1,  1,  0,  0]])

In [9]:
Classes=[]
for i in range(amostra.shape[0]):
        MonomiosDaObs=[]
        for j in previsores_classes:
            #Monomio particular pra saber se é 0 ou 1.
            MonomioTemporario=1
            #Acessando os literais do monomio.
            for k in range(p):
                #Caso que o literal seja normal, o mesmo da variavel especifica
                #da observacao.
                if j[k]==1:
                    MonomioTemporario*=amostra[i,k]
                #Caso que o literal muda o numero da variavel especifica
                #da observacao
                elif j[k]==-1 and amostra[i,k]==0:          
                    MonomioTemporario*=1
                elif j[k]==-1 and amostra[i,k]==1:
                    MonomioTemporario*=0
                else:
                    continue
            MonomiosDaObs.append(MonomioTemporario)
        if 1 in MonomiosDaObs:
            Classes.append(1)
        else:
            Classes.append(0)
Classes


[1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1]

In [10]:
monomios_a_remover =[]
#Acessando os indices das observacoes.
for i in range(amostra.shape[0]):
    #Verificando somente as observacoes que as classes dao 0.
    if Classes[i]==0:
        #Acessando os indices dos monomios 
        for j in range(Monomios.shape[0]):
            #Monomio particular pra saber se é 0 ou 1.
            MonomioTemporario=1
            #Acessando os indices dos literais do monomio.
            for w in range(p):
                #Caso que o literal seja normal, o mesmo da variavel especifica
                #da observacao.
                if Monomios[j][w]==1:
                    MonomioTemporario*=amostra[i,w]
                #Caso que o literal muda o numero da variavel especifica
                #da observacao
                elif Monomios[j][w]==-1 and amostra[i,w]==0:
                    MonomioTemporario*=1
                elif Monomios[j][w]==-1 and amostra[i,w]==1:
                    MonomioTemporario*=0
                else:
                    continue
            if MonomioTemporario==1:
                if j not in monomios_a_remover:
                    monomios_a_remover.append(j)


In [11]:
#Disjuncao de monomios de no maximo grau k que preve as classes. 
#Funcao setdiff1d faz a diferenca de conjuntos, eu fiz com que somente apareca
#os monomios que dao certo para as observacoes de classe 0.                
disjuncao_monomios=Monomios[np.setdiff1d(np.arange(Monomios.shape[0]),np.array(monomios_a_remover))]
print("A funcao de disjuncao de monomomios é: \n",disjuncao_monomios,"\n")
print("A funcao de disjuncao de monomomios que gerou as classes é: \n",previsores_classes)
#Processo para ver se a disjuncao acerta todas as classes.
Acertos=0              
for i in range(amostra.shape[0]):
    MonomiosDaObs=[]
    for j in range(disjuncao_monomios.shape[0]):
        #Monomio particular pra saber se é 0 ou 1.
        MonomioTemporario=1
        #Acessando os literais do monomio.
        for w in range(p):
            #Caso que o literal seja normal, o mesmo da variavel especifica
            #da observacao.
            if disjuncao_monomios[j][w]==1:
                MonomioTemporario*=amostra[i,w]
            #Caso que o literal muda o numero da variavel especifica
            #da observacao
            elif disjuncao_monomios[j][w]==-1 and amostra[i,w]==0:          
                MonomioTemporario*=1
            elif disjuncao_monomios[j][w]==-1 and amostra[i,w]==1:          
                MonomioTemporario*=0
            else:
                continue
        MonomiosDaObs.append(MonomioTemporario)
    if Classes[i]==1 and (1 in MonomiosDaObs):
        Acertos+=1
    elif Classes[i]==0 and (1 not in MonomiosDaObs):
        Acertos+=1
    else:
        continue
if Acertos==amostra.shape[0]:
    print("A funcao de disjuncao de monomios acertou todos os exemplos!") 

A funcao de disjuncao de monomomios é: 
 [[-1 -1 -1 ...  0  0  0]
 [-1 -1  0 ...  0  0  0]
 [-1 -1  0 ...  0  0  0]
 ...
 [ 1  0  1 ...  0  0  0]
 [ 1  1 -1 ...  0  0  0]
 [ 1  1  0 ...  0  0  0]] 

A funcao de disjuncao de monomomios que gerou as classes é: 
 [[ 0  0  0  0 -1  0  0  0]
 [ 0  1  0  0 -1  1  0  0]
 [ 0  0 -1  0  1 -1  0  0]
 [ 0 -1  0  0  1  0  0  0]
 [ 0  0 -1  0  1  1  0  0]]
A funcao de disjuncao de monomios acertou todos os exemplos!
